# Generated by Django 2.2.1 on 2022-04-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='adminname',
            field=models.CharField(max_length=11, unique=True, verbose_name='管理员'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20, verbose_name='任务名')),
                ('msg', models.TextField(verbose_name='任务描述')),
                ('status', models.SmallIntegerField(choices=[(1, '未完成'), (2, '已完成'), (3, '待完成')], default=1, verbose_name='状态')),
                ('depart', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apptest.Department', verbose_name='部门')),
            ],
        ),
    ]
